### ISSUE TITLE
Use the conversations.csv to get the conversation IDs

### ISSUE THREAD

**Issue by thephm** [thephm/signal_sqlite_md#1]
The current implementation requires the definition of each conversation mapped to a person so the messages file can be parsed.

There are two issues:

1. It's a pain to have to go into the `conversations.csv` file, copy and paste those into the config file
3. The conversation IDs can change over time (I think)

Since the person's phone number is also in the `converstions.csv` file inside the `e164` field, just parse this CSV file and find the corresponding conversation IDs, keep those with each person.

**Comment by thephm** [comment]
and the `serviceId` for each person which is used in group messages

**Comment by magnuzno** [comment]
Is it possible to provide an option to pull conversations between people that are not included in the people.json file? I'm trying to adapt this tool to build a summary of large discussions. There are over a hundred participants in a particular group. I am trying to avoid manually adding their slugs to people.json one by one...

**Comment by thephm** [comment]
> What would be needed output messages where at least one person is not included in the people.json file? I'm trying to adapt this tool to build a summary of large discussions. There are over a hundred participants in a particular group. I am trying to avoid manually adding their slugs to people.json one by one...

I started looking at it. The `conversations.csv` file which has `79` rows. 

There are 4 x name columns (fields): `name, profileName, familyName, fullName`. In my file there are quantities `45, 30, 16, 30` of them, respectively. Sometimes the `profileName` are the same (qty `9`), others it's just their first name (qty `14`). I am thinking to use `fullName` first, making it `snake_case`. If not there, use `profileName`. If no `profileName` I won't include them, why?

Because, for some reason I see a bunch of people (`25`) in my `conversations.csv` that are not Signal contacts. They look like people I have in my contacts who are on Signal but for which I haven't had conversations 🤣

**Comment by thephm** [comment]
Implemented the option `-a` which includes people not in the `people.json`. I suppose it should also add them to the `people.json` but for now it just includes their messages in the converted Markdown files.
